# Generated by Django 2.0.1 on 2024-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20240511_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='photo',
            field=models.ImageField(default='/default_photo.png', upload_to='medications/'),
        ),
    ]
