# Generated by Django 2.0.1 on 2024-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medication_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='instruction',
        ),
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(default='Adults', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='photo',
            field=models.ImageField(default='default_photo.png', upload_to='medications_photo/'),
        ),
    ]
