# Generated by Django 2.0.1 on 2024-05-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20240511_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='instruction',
            field=models.TextField(default='1 per day'),
        ),
    ]
