# Generated by Django 2.0.1 on 2024-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_medication_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('number_of_employees', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='default_photo.png', upload_to='departments_photo/')),
            ],
        ),
    ]
