# Generated by Django 2.0.1 on 2024-05-11 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pickuppoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_sold', models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 42, 33, 883927))),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.PickupPoint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='purchases',
            field=models.ManyToManyField(to='pharmacy.Purchase'),
        ),
    ]
