# Generated by Django 2.0.1 on 2024-05-11 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20240511_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 45, 22, 618209)),
        ),
    ]
