# Generated by Django 2.0.1 on 2024-05-12 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_auto_20240512_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='+37525', max_length=18),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 13, 46, 53, 533243)),
        ),
    ]
